name = "CFCompressible"
uuid = "a33e4613-43be-4f0e-b500-138f013d70af"
authors = ["Thomas Dubos <thomas.dubos@polytechnique.edu>"]
version = "0.1.0"

[deps]
CFDomains = "3699aaca-035b-4155-96ec-eecb526248de"
ManagedLoops = "36a4119d-6b73-4371-88fe-ba2d91f5495d"

[compat]
CFDomains = "0.3.4"
ManagedLoops = "0.1.13"
