choices = (Fluid=IdealPerfectGas,
           TimeScheme=ARK_TRBDF2, # ARK_TRBDF2, # Midpoint, #BackwardEuler, # KinnmarkGray{2,5},
           consvar=:temperature,
           TestCase=Jablonowski06,
           Prec=Float64,
           nz=30,
           hyperdiff_n=3,
           remap_period=0,
           nlat=64,
           ndays=3, # 6,
           newton=(niter=10,         # number of iterations
                   flip_solve=true, # direction of tridiagonal solver passes  
                   update_W=true,   # update W during Newton iterations
                   verbose=true))
params = (
          ptop = 225.52395239472398,
          pb=1e5,
          rhob=1e6,
          gravity=9.81,
          Phis=0,
          Cp=1000,
          kappa=2 / 7,
          p0=1e5,
          T0=300,
          radius=6.4e6,
          Omega=7.272e-5,
          hyperdiff_nu=0, # 0.002,
          courant=1.0, # 3.0,
          dt=1000,
          interval=6 * 3600)
